import type { IndustrySeed, IndustrySource } from './types';

const checkedAt = '2026-08-15';

const source = (
  label: string,
  url: string,
  sourceType: IndustrySource['sourceType'],
  ...supports: string[]
): IndustrySource => ({ label, url, sourceType, supports, checkedAt });

export const industrySeeds: IndustrySeed[] = [
  {
    slug: 'aesthetics-clinics',
    name: 'Aesthetics clinics',
    singularName: 'aesthetics clinic',
    group: 'Health and care',
    shortDescription: 'Clinics offering non-surgical cosmetic consultations and treatments where practitioner identity, treatment scope, product information and safe enquiry routes must be clear.',
    pageAudience: ['clinic owners', 'practice managers', 'responsible clinicians'],
    decisionMakers: ['founder or medical director', 'clinic manager', 'marketing lead'],
    commonServices: ['anti-wrinkle consultations', 'dermal filler treatments', 'skin consultations', 'chemical peels', 'laser hair reduction', 'microneedling', 'medical-grade skincare', 'aftercare reviews'],
    buyerConcerns: ['the qualifications and role of the treating practitioner', 'which treatments are offered at the named location', 'consultation, consent and aftercare arrangements', 'whether promotional claims are responsible and specific', 'how product and medicine information is presented', 'how a prospective patient can ask a clinical question safely'],
    actionPaths: ['request a consultation', 'ask a treatment suitability question', 'book an aftercare review', 'contact the clinic about accessibility'],
    automationBoundaries: ['clinical suitability decisions require an appropriately qualified human', 'prescription-only medicine promotion and supply must not be automated as ordinary retail', 'urgent adverse-event or safeguarding concerns need a human escalation route'],
    trustedSources: [
      source('Care Quality Commission service finder', 'https://www.cqc.org.uk/care-services', 'regulator', 'registered provider identity and inspection information where CQC regulation applies'),
      source('Advertising Standards Authority cosmetic interventions guidance', 'https://www.asa.org.uk/advice-online/cosmetic-interventions.html', 'regulator', 'responsible advertising boundaries for cosmetic interventions'),
      source('Medicines and Healthcare products Regulatory Agency', 'https://www.gov.uk/government/organisations/medicines-and-healthcare-products-regulatory-agency', 'government', 'medicine and medical-device safety information'),
      source('Joint Council for Cosmetic Practitioners register', 'https://www.jccp.org.uk/PractitionerRegister', 'professional-body', 'voluntary practitioner registration where applicable'),
    ],
    relatedIndustries: ['private-medical-clinics', 'dental-practices', 'physiotherapy-clinics'],
  },
  {
    slug: 'dental-practices',
    name: 'Dental practices',
    singularName: 'dental practice',
    group: 'Health and care',
    shortDescription: 'NHS, private and mixed dental practices that need treatment scope, clinician registration, access arrangements and booking information to remain consistent across public sources.',
    pageAudience: ['practice owners', 'practice managers', 'dental groups'],
    decisionMakers: ['principal dentist', 'practice manager', 'operations director'],
    commonServices: ['routine examinations', 'hygiene appointments', 'restorative dentistry', 'root canal treatment', 'crowns and bridges', 'dental implants', 'orthodontic treatment', 'emergency dental appointments'],
    buyerConcerns: ['whether the practice accepts new NHS, private or mixed patients', 'which clinicians provide a named treatment', 'current opening hours and emergency access', 'treatment fees and consultation steps', 'accessibility and location information', 'how to book, change or cancel an appointment'],
    actionPaths: ['request a new-patient appointment', 'book an emergency assessment', 'ask about a named treatment', 'contact the practice about access needs'],
    automationBoundaries: ['diagnosis and treatment suitability require a registered dental professional', 'urgent pain, swelling or trauma needs appropriate clinical triage', 'fee estimates must not be presented as a final clinical treatment plan'],
    trustedSources: [
      source('General Dental Council register', 'https://olr.gdc-uk.org/', 'regulator', 'dental professional registration and specialist-list status'),
      source('Care Quality Commission service finder', 'https://www.cqc.org.uk/care-services', 'regulator', 'provider registration, inspection information and locations in England'),
      source('NHS Find a dentist', 'https://www.nhs.uk/service-search/find-a-dentist', 'official-directory', 'public dental service discovery and location information'),
      source('General Dental Council standards and guidance', 'https://www.gdc-uk.org/standards-guidance', 'regulator', 'professional standards and scope guidance'),
    ],
    relatedIndustries: ['aesthetics-clinics', 'private-medical-clinics', 'physiotherapy-clinics'],
  },
  {
    slug: 'domiciliary-care-providers',
    name: 'Domiciliary care providers',
    singularName: 'domiciliary care provider',
    group: 'Health and care',
    shortDescription: 'Home-care organisations whose regulated activity, service area, care scope, inspection evidence and referral pathway must be easy for families and commissioners to verify.',
    pageAudience: ['registered providers', 'care operations teams', 'home-care branches'],
    decisionMakers: ['registered manager', 'nominated individual', 'operations director'],
    commonServices: ['personal care visits', 'medication support', 'meal preparation', 'companionship', 'live-in care', 'respite care', 'hospital discharge support', 'night care'],
    buyerConcerns: ['whether the provider is registered for the relevant activity', 'the exact towns or postcodes served', 'minimum visit lengths and availability', 'how assessments and care plans are agreed', 'inspection findings and provider identity', 'how families, professionals or commissioners make a referral'],
    actionPaths: ['request a care assessment', 'make a professional referral', 'ask about service-area availability', 'raise a safeguarding or service concern'],
    automationBoundaries: ['care needs and risk assessments require qualified human oversight', 'safeguarding concerns must reach the designated human process', 'availability cannot be promised until staffing and care requirements are reviewed'],
    trustedSources: [
      source('CQC personal care registration guidance', 'https://www.cqc.org.uk/guidance-regulation/providers/registration/personal-care-registration-homecare-agencies', 'regulator', 'registration expectations for home-care agencies providing personal care'),
      source('Care Quality Commission service finder', 'https://www.cqc.org.uk/care-services', 'regulator', 'inspection reports, ratings, service locations and provider identity'),
      source('Skills for Care', 'https://www.skillsforcare.org.uk/', 'professional-body', 'adult social care workforce guidance and sector standards'),
      source('NICE home care guidance', 'https://www.nice.org.uk/guidance/ng21', 'technical-standard', 'person-centred home-care planning and delivery guidance'),
    ],
    relatedIndustries: ['recruitment-agencies', 'private-medical-clinics', 'commercial-cleaning-companies'],
  },
  {
    slug: 'physiotherapy-clinics',
    name: 'Physiotherapy clinics',
    singularName: 'physiotherapy clinic',
    group: 'Health and care',
    shortDescription: 'Clinics where protected professional titles, practitioner credentials, treatment specialisms, referral requirements and appointment pathways should be unambiguous.',
    pageAudience: ['clinic owners', 'lead physiotherapists', 'multi-site therapy groups'],
    decisionMakers: ['clinical director', 'practice manager', 'founder'],
    commonServices: ['musculoskeletal assessment', 'sports injury rehabilitation', 'post-operative rehabilitation', 'pelvic health physiotherapy', 'neurological physiotherapy', 'respiratory physiotherapy', 'workplace assessments', 'home visits'],
    buyerConcerns: ['whether the practitioner is on the relevant professional register', 'which clinical specialisms are available', 'whether self-referral is accepted', 'appointment location, format and accessibility', 'fees, insurance recognition and cancellation terms', 'how urgent or unsuitable symptoms are redirected'],
    actionPaths: ['book an initial assessment', 'ask about a clinical specialism', 'submit an insurer or professional referral', 'request a home or workplace visit'],
    automationBoundaries: ['clinical diagnosis and treatment planning require a registered professional', 'red-flag symptoms need human triage and appropriate escalation', 'insurance eligibility must be confirmed rather than inferred'],
    trustedSources: [
      source('HCPC check the register', 'https://www.hcpc-uk.org/check-the-register/', 'regulator', 'registration of physiotherapists using the protected title'),
      source('Chartered Society of Physiotherapy directory', 'https://www.csp.org.uk/public-patient/find-physiotherapist', 'professional-body', 'chartered physiotherapist discovery and practice information'),
      source('Care Quality Commission service finder', 'https://www.cqc.org.uk/care-services', 'regulator', 'provider information where regulated activities bring a service into scope'),
      source('NICE musculoskeletal guidance', 'https://www.nice.org.uk/guidance/conditions-and-diseases/musculoskeletal-conditions', 'technical-standard', 'evidence-based guidance relevant to musculoskeletal pathways'),
    ],
    relatedIndustries: ['private-medical-clinics', 'dental-practices', 'aesthetics-clinics'],
  },
  {
    slug: 'private-medical-clinics',
    name: 'Private medical clinics',
    singularName: 'private medical clinic',
    group: 'Health and care',
    shortDescription: 'Independent clinics that must distinguish consultation scope, clinician credentials, regulated locations, fees and onward-care pathways without making unsupported outcome claims.',
    pageAudience: ['clinic owners', 'medical directors', 'independent healthcare groups'],
    decisionMakers: ['medical director', 'registered manager', 'operations lead'],
    commonServices: ['general medical consultations', 'specialist consultations', 'diagnostic testing', 'health screening', 'minor procedures', 'vaccination services', 'occupational health', 'follow-up care'],
    buyerConcerns: ['which clinician and speciality will handle the enquiry', 'whether the location and activity are appropriately registered', 'what is included in the stated fee', 'how tests, prescriptions and follow-up are arranged', 'whether insurer authorisation is required', 'how urgent symptoms and emergencies are handled'],
    actionPaths: ['request a consultation', 'upload or arrange a referral', 'ask for fee and test information', 'contact the clinic about follow-up care'],
    automationBoundaries: ['clinical diagnosis, prescribing and treatment decisions require an authorised clinician', 'urgent symptoms need a clear emergency redirection rather than automated reassurance', 'insurance and test costs require case-specific confirmation'],
    trustedSources: [
      source('General Medical Council medical register', 'https://www.gmc-uk.org/registration-and-licensing/the-medical-register', 'regulator', 'doctor registration, licence and specialist or GP register information'),
      source('Care Quality Commission service finder', 'https://www.cqc.org.uk/care-services', 'regulator', 'registered provider, location, inspection and rating information in England'),
      source('NHS service search', 'https://www.nhs.uk/service-search/', 'official-directory', 'public healthcare service information and onward routes'),
      source('CMA private healthcare market investigation', 'https://www.gov.uk/cma-cases/private-healthcare-market-investigation', 'government', 'competition and information requirements in private healthcare'),
    ],
    relatedIndustries: ['aesthetics-clinics', 'physiotherapy-clinics', 'dental-practices'],
  },
  {
    slug: 'veterinary-practices',
    name: 'Veterinary practices',
    singularName: 'veterinary practice',
    group: 'Health and care',
    shortDescription: 'Practices where species coverage, clinical services, emergency arrangements, professional registration and medicine boundaries need to be explicit for animal owners.',
    pageAudience: ['practice owners', 'practice managers', 'veterinary groups'],
    decisionMakers: ['clinical director', 'practice manager', 'operations director'],
    commonServices: ['routine consultations', 'vaccinations', 'preventive health plans', 'diagnostic imaging', 'surgery', 'dentistry', 'emergency care', 'referrals'],
    buyerConcerns: ['which species and conditions the practice can see', 'how out-of-hours emergencies are handled', 'which professionals are registered', 'consultation, treatment and medicine costs', 'availability of diagnostics or referral pathways', 'how to register an animal and book'],
    actionPaths: ['register a pet', 'book a routine consultation', 'contact the emergency service', 'request a referral or records transfer'],
    automationBoundaries: ['diagnosis, prescribing and clinical advice require a veterinary professional', 'emergencies need immediate human-led triage', 'medicine availability and pricing must be confirmed for the individual case'],
    trustedSources: [
      source('RCVS Find a Vet', 'https://findavet.rcvs.org.uk/home/', 'official-directory', 'registered veterinary practices and professionals'),
      source('RCVS Code of Professional Conduct', 'https://www.rcvs.org.uk/setting-standards/advice-and-guidance/code-of-professional-conduct-for-veterinary-surgeons/', 'regulator', 'professional responsibilities and public information boundaries'),
      source('CMA veterinary services market investigation', 'https://www.gov.uk/cma-cases/veterinary-services-market-for-pets-investigation', 'government', 'competition and consumer-information issues in veterinary services'),
      source('Veterinary Medicines Directorate', 'https://www.gov.uk/government/organisations/veterinary-medicines-directorate', 'government', 'veterinary medicine regulation and safety information'),
    ],
    relatedIndustries: ['private-medical-clinics', 'dental-practices', 'recruitment-agencies'],
  },
  {
    slug: 'accountancy-firms',
    name: 'Accountancy firms',
    singularName: 'accountancy firm',
    group: 'Professional and financial services',
    shortDescription: 'Firms that need service scope, professional memberships, sector experience, fee basis and secure client-onboarding routes to be described precisely.',
    pageAudience: ['accountancy practice owners', 'tax advisers', 'outsourced finance teams'],
    decisionMakers: ['managing partner', 'practice director', 'marketing partner'],
    commonServices: ['annual accounts', 'self assessment', 'corporation tax', 'VAT returns', 'payroll', 'bookkeeping', 'management accounts', 'business advisory'],
    buyerConcerns: ['which client types and sectors the firm serves', 'which professional bodies or authorisations apply', 'whether tax, audit or insolvency work is within scope', 'how fees and engagement terms are structured', 'what software and records are supported', 'how confidential documents are exchanged securely'],
    actionPaths: ['request an initial consultation', 'ask for a fee proposal', 'send a secure onboarding enquiry', 'switch accountant and arrange records transfer'],
    automationBoundaries: ['tax positions and filings require professional review and client approval', 'professional membership or audit status must never be inferred', 'confidential financial records require an approved secure channel'],
    trustedSources: [
      source('HMRC standard for agents', 'https://www.gov.uk/government/publications/hmrc-the-standard-for-agents', 'government', 'minimum standards expected of tax agents'),
      source('ICAEW Find a Chartered Accountant', 'https://find.icaew.com/', 'official-directory', 'ICAEW member and firm discovery where applicable'),
      source('ACCA Find an accountant', 'https://www.accaglobal.com/gb/en/member/find-an-accountant.html', 'official-directory', 'ACCA member and firm discovery where applicable'),
      source('Companies House service', 'https://find-and-update.company-information.service.gov.uk/', 'government', 'legal entity and filing information'),
    ],
    relatedIndustries: ['financial-advisers', 'solicitors', 'mortgage-brokers'],
  },
  {
    slug: 'solicitors',
    name: 'Solicitors',
    singularName: 'solicitors firm',
    group: 'Professional and financial services',
    shortDescription: 'Legal practices where regulated identity, areas of law, jurisdiction, lawyer credentials, costs information and enquiry boundaries need careful, verifiable wording.',
    pageAudience: ['law firm partners', 'practice managers', 'legal operations teams'],
    decisionMakers: ['managing partner', 'practice manager', 'business development director'],
    commonServices: ['conveyancing', 'family law', 'employment law', 'commercial contracts', 'dispute resolution', 'wills and probate', 'immigration law', 'criminal defence'],
    buyerConcerns: ['whether the firm and individual are regulated', 'which areas of law and jurisdictions are covered', 'who will handle the matter', 'how costs and funding options are explained', 'whether the firm accepts the type and urgency of matter', 'how conflicts checks and confidential intake begin'],
    actionPaths: ['request an initial legal consultation', 'submit a confidential matter summary', 'ask about costs and funding', 'contact the firm about an urgent deadline'],
    automationBoundaries: ['legal advice and case acceptance require an authorised human', 'conflicts checks must occur before confidential detail is invited or relied upon', 'outcomes, timescales and costs cannot be guaranteed by an automated response'],
    trustedSources: [
      source('SRA Solicitors Register', 'https://www.sra.org.uk/consumers/register/', 'regulator', 'regulated firm and solicitor records'),
      source('Law Society Find a Solicitor', 'https://solicitors.lawsociety.org.uk/', 'official-directory', 'practice areas, locations and accredited services where listed'),
      source('Legal Ombudsman', 'https://www.legalombudsman.org.uk/', 'regulator', 'consumer complaint routes and service expectations'),
      source('GOV.UK legal aid finder', 'https://www.gov.uk/check-legal-aid', 'government', 'official legal-aid eligibility and service routes'),
    ],
    relatedIndustries: ['accountancy-firms', 'estate-agents', 'mortgage-brokers'],
  },
  {
    slug: 'estate-agents',
    name: 'Estate agents',
    singularName: 'estate agency',
    group: 'Professional and financial services',
    shortDescription: 'Sales, lettings and property-management firms whose branch coverage, services, fees, redress membership and valuation or viewing routes must remain current.',
    pageAudience: ['independent agencies', 'multi-branch estate agents', 'lettings teams'],
    decisionMakers: ['agency owner', 'branch director', 'marketing director'],
    commonServices: ['residential sales', 'lettings', 'property management', 'market appraisals', 'tenant finding', 'new homes sales', 'auction services', 'landlord compliance support'],
    buyerConcerns: ['which branches and postcodes the agency covers', 'whether it handles sales, lettings or both', 'fees and service inclusions', 'redress-scheme membership and complaints route', 'how valuations and viewings are arranged', 'how property particulars and availability stay current'],
    actionPaths: ['request a market appraisal', 'book a property viewing', 'register as a buyer or tenant', 'ask for landlord service details'],
    automationBoundaries: ['valuations require property-specific professional judgement', 'property availability and offer status must be confirmed against the live system', 'identity, anti-money-laundering and tenancy checks require controlled processes'],
    trustedSources: [
      source('GOV.UK property-agent redress guidance', 'https://www.gov.uk/redress-scheme-estate-agencies', 'government', 'approved redress-scheme requirements'),
      source('The Property Ombudsman member search', 'https://www.tpos.co.uk/find-a-member', 'official-directory', 'member agency verification'),
      source('Property Redress Scheme member list', 'https://www.theprs.co.uk/consumer/members/', 'official-directory', 'member agency verification'),
      source('National Trading Standards Estate and Letting Agency Team', 'https://www.nationaltradingstandards.uk/work-areas/estate-agency/', 'regulator', 'estate-agency enforcement and material-information guidance'),
    ],
    relatedIndustries: ['mortgage-brokers', 'solicitors', 'building-contractors'],
  },
  {
    slug: 'mortgage-brokers',
    name: 'Mortgage brokers',
    singularName: 'mortgage broker',
    group: 'Professional and financial services',
    shortDescription: 'Mortgage advisers whose regulated status, market scope, fees, lender access, customer types and enquiry process need accurate qualification language.',
    pageAudience: ['brokerage owners', 'appointed representatives', 'mortgage advisory teams'],
    decisionMakers: ['principal adviser', 'compliance director', 'brokerage owner'],
    commonServices: ['first-time buyer mortgages', 'home mover mortgages', 'remortgages', 'buy-to-let mortgages', 'self-employed applications', 'adverse-credit cases', 'protection referrals', 'later-life lending referrals'],
    buyerConcerns: ['whether the firm and adviser appear on the FCA Register', 'which mortgage types and customer circumstances are served', 'whether advice covers the whole market or a defined panel', 'broker fees and when they become payable', 'documents required for an initial review', 'how regulated advice and lender decisions are separated'],
    actionPaths: ['request an initial mortgage review', 'ask about broker fees', 'submit a fact-find enquiry', 'book a document-readiness call'],
    automationBoundaries: ['personal recommendations require regulated advice and suitability assessment', 'eligibility and lending decisions remain subject to lender criteria', 'illustrations and rates must be current and appropriately controlled'],
    trustedSources: [
      source('FCA Financial Services Register', 'https://register.fca.org.uk/s/', 'regulator', 'firm, individual and appointed-representative status'),
      source('MoneyHelper mortgage adviser guidance', 'https://www.moneyhelper.org.uk/en/homes/buying-a-home/choosing-a-mortgage-shop-around-or-get-advice', 'government', 'consumer guidance on mortgage advice and comparison'),
      source('Financial Ombudsman Service mortgages', 'https://www.financial-ombudsman.org.uk/consumers/complaints-can-help/mortgages', 'regulator', 'mortgage complaint scope and consumer routes'),
      source('Financial Services Compensation Scheme', 'https://www.fscs.org.uk/check/check-your-money-is-protected/', 'official-directory', 'consumer protection checks where applicable'),
    ],
    relatedIndustries: ['estate-agents', 'financial-advisers', 'solicitors'],
  },
  {
    slug: 'financial-advisers',
    name: 'Financial advisers',
    singularName: 'financial adviser',
    group: 'Professional and financial services',
    shortDescription: 'Advice firms that must present regulatory permissions, client scope, adviser credentials, charging basis and advice boundaries without implying outcomes.',
    pageAudience: ['financial advice firms', 'independent advisers', 'wealth-planning practices'],
    decisionMakers: ['principal adviser', 'compliance officer', 'managing director'],
    commonServices: ['retirement planning', 'investment advice', 'pension advice', 'protection planning', 'estate planning coordination', 'cash-flow planning', 'workplace financial education', 'ongoing reviews'],
    buyerConcerns: ['whether the firm and adviser are authorised for the relevant activity', 'which client profiles and advice areas are served', 'independent or restricted advice status', 'initial and ongoing charging structure', 'minimum asset or engagement requirements', 'how personal recommendations and risk discussions are conducted'],
    actionPaths: ['request an initial discovery meeting', 'ask for a service and fee guide', 'submit a secure planning enquiry', 'book an existing-client review'],
    automationBoundaries: ['personal recommendations require regulated suitability work', 'investment performance and outcomes cannot be promised', 'sensitive financial information needs a secure, approved collection route'],
    trustedSources: [
      source('FCA Financial Services Register', 'https://register.fca.org.uk/s/', 'regulator', 'authorisation, permissions and individual status'),
      source('MoneyHelper choosing a financial adviser', 'https://www.moneyhelper.org.uk/en/getting-help-and-advice/financial-advisers/choosing-a-financial-adviser', 'government', 'consumer checks, adviser types and charging questions'),
      source('Financial Services Compensation Scheme', 'https://www.fscs.org.uk/check/check-your-money-is-protected/', 'official-directory', 'protection checks where applicable'),
      source('Financial Ombudsman Service investments', 'https://www.financial-ombudsman.org.uk/consumers/complaints-can-help/investments', 'regulator', 'complaint routes for investment and advice services'),
    ],
    relatedIndustries: ['mortgage-brokers', 'accountancy-firms', 'solicitors'],
  },
  {
    slug: 'recruitment-agencies',
    name: 'Recruitment agencies',
    singularName: 'recruitment agency',
    group: 'Business services',
    shortDescription: 'Recruiters whose sector coverage, permanent or temporary model, worker terms, employer process and live vacancy actions need separate, current explanations.',
    pageAudience: ['recruitment founders', 'agency directors', 'specialist staffing teams'],
    decisionMakers: ['managing director', 'operations director', 'marketing lead'],
    commonServices: ['permanent recruitment', 'temporary staffing', 'contract recruitment', 'executive search', 'candidate sourcing', 'payroll coordination', 'workforce planning', 'recruitment process outsourcing'],
    buyerConcerns: ['which sectors, roles and locations the agency covers', 'whether it acts as an employment agency or employment business', 'candidate and hirer terms', 'live-vacancy accuracy and application routes', 'screening, qualification and reference processes', 'how personal data and candidate records are handled'],
    actionPaths: ['submit a vacancy brief', 'apply for a live role', 'register as a candidate', 'ask about temporary staffing availability'],
    automationBoundaries: ['final hiring and suitability decisions require accountable humans', 'candidate screening must avoid unlawful discrimination and opaque automated rejection', 'right-to-work, qualification and reference evidence requires controlled verification'],
    trustedSources: [
      source('GOV.UK employment agencies and businesses', 'https://www.gov.uk/employment-agencies-and-businesses/overview', 'government', 'rules for employment agencies and employment businesses'),
      source('Employment Agency Standards Inspectorate', 'https://www.gov.uk/government/organisations/employment-agency-standards-inspectorate', 'regulator', 'sector enforcement and worker complaint information'),
      source('Recruitment and Employment Confederation directory', 'https://www.rec.uk.com/recruiters/member-directory', 'professional-body', 'REC member discovery where applicable'),
      source('ICO employment practices and data protection', 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/employment/', 'regulator', 'worker and candidate data-protection guidance'),
    ],
    relatedIndustries: ['domiciliary-care-providers', 'training-providers', 'managed-it-service-providers'],
  },
  {
    slug: 'managed-it-service-providers',
    name: 'Managed IT service providers',
    singularName: 'managed IT service provider',
    group: 'Business services',
    shortDescription: 'MSPs that need service boundaries, support coverage, security responsibilities, certifications, response routes and onboarding expectations stated with technical precision.',
    pageAudience: ['MSP founders', 'IT support companies', 'cybersecurity service teams'],
    decisionMakers: ['managing director', 'technical director', 'service delivery manager'],
    commonServices: ['managed helpdesk', 'Microsoft 365 support', 'cloud administration', 'endpoint management', 'network management', 'cybersecurity monitoring', 'backup management', 'incident response coordination'],
    buyerConcerns: ['which users, devices and platforms are supported', 'support hours and response definitions', 'security certifications and shared responsibilities', 'backup, recovery and incident processes', 'contract term, onboarding and exit arrangements', 'how to request support or report an incident'],
    actionPaths: ['request an IT assessment', 'submit a managed-support enquiry', 'report a security incident through the approved channel', 'ask for service-level and onboarding details'],
    automationBoundaries: ['privileged access changes require strong authentication and approval', 'security incidents need human-led triage and evidence preservation', 'service-level claims must match the signed contract and monitoring method'],
    trustedSources: [
      source('NCSC choosing a managed service provider', 'https://www.ncsc.gov.uk/guidance/choosing-a-managed-service-provider-msp', 'government', 'MSP due diligence, contracts and security responsibilities'),
      source('NCSC Cyber Essentials overview', 'https://www.ncsc.gov.uk/cyberessentials/overview', 'technical-standard', 'government-backed baseline cyber controls'),
      source('ICO security guidance', 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/security/', 'regulator', 'personal-data security responsibilities'),
      source('NCSC cloud security guidance', 'https://www.ncsc.gov.uk/collection/cloud', 'technical-standard', 'cloud security principles and shared-responsibility context'),
    ],
    relatedIndustries: ['accountancy-firms', 'recruitment-agencies', 'training-providers'],
  },
  {
    slug: 'training-providers',
    name: 'Training providers',
    singularName: 'training provider',
    group: 'Business services',
    shortDescription: 'Commercial, vocational and regulated learning providers whose course outcomes, awarding relationships, delivery format, eligibility and enrolment routes must be distinguished.',
    pageAudience: ['training-company founders', 'learning providers', 'apprenticeship teams'],
    decisionMakers: ['managing director', 'quality director', 'head of enrolment'],
    commonServices: ['classroom courses', 'live online training', 'self-paced learning', 'vocational qualifications', 'apprenticeship training', 'compliance training', 'leadership development', 'custom employer programmes'],
    buyerConcerns: ['whether the course is accredited, regulated or unregulated', 'entry requirements and learner eligibility', 'delivery dates, location and format', 'total fees and funding availability', 'assessment, certification and completion terms', 'how employers or individuals enrol'],
    actionPaths: ['request a course prospectus', 'check eligibility and funding', 'enrol on a scheduled course', 'ask for an employer programme proposal'],
    automationBoundaries: ['admissions and funding eligibility require evidence-based human checks', 'achievement or employment outcomes cannot be guaranteed', 'regulated qualification claims must match the awarding or regulatory record'],
    trustedSources: [
      source('UK Register of Learning Providers', 'https://www.ukrlp.co.uk/', 'official-directory', 'learning-provider reference records'),
      source('Ofqual Register of Regulated Qualifications', 'https://register.ofqual.gov.uk/', 'regulator', 'regulated qualifications and awarding organisations'),
      source('GOV.UK Find apprenticeship training', 'https://findapprenticeshiptraining.apprenticeships.education.gov.uk/', 'official-directory', 'approved apprenticeship training options'),
      source('GOV.UK apprenticeship provider guidance', 'https://www.gov.uk/guidance/register-of-apprenticeship-training-providers', 'government', 'provider-register expectations and status'),
    ],
    relatedIndustries: ['recruitment-agencies', 'managed-it-service-providers', 'accountancy-firms'],
  },
  {
    slug: 'plumbing-heating-firms',
    name: 'Plumbing and heating firms',
    singularName: 'plumbing and heating firm',
    group: 'Local and home services',
    shortDescription: 'Local contractors whose gas scope, engineer credentials, coverage area, emergency availability and quote route must be clear without implying unverified accreditation.',
    pageAudience: ['plumbing business owners', 'heating contractors', 'local service teams'],
    decisionMakers: ['owner-manager', 'operations manager', 'service coordinator'],
    commonServices: ['boiler servicing', 'boiler replacement', 'central-heating repairs', 'general plumbing repairs', 'leak diagnosis', 'bathroom plumbing', 'hot-water cylinder work', 'emergency call-outs'],
    buyerConcerns: ['whether gas work is carried out by an appropriately registered engineer', 'which towns and postcodes are served', 'emergency hours and call-out terms', 'whether the firm handles the specific appliance or system', 'how estimates, diagnostics and parts are charged', 'how to request a visit and provide safe access information'],
    actionPaths: ['request a repair visit', 'ask for a boiler quote', 'book planned servicing', 'contact the emergency call-out line'],
    automationBoundaries: ['gas safety and diagnosis require a competent registered engineer where applicable', 'emergency availability must be confirmed rather than assumed', 'quotes may need an inspection before scope and price are final'],
    trustedSources: [
      source('Gas Safe Register', 'https://www.gassaferegister.co.uk/find-an-engineer-or-check-the-register/', 'official-directory', 'engineer and business registration for in-scope gas work'),
      source('WaterSafe approved plumber directory', 'https://www.watersafe.org.uk/find-a-plumber/', 'official-directory', 'approved plumbing businesses where listed'),
      source('CIPHE Find a plumber', 'https://www.ciphe.org.uk/professional-members/find-a-plumber/', 'professional-body', 'professional member discovery where applicable'),
      source('GOV.UK Competent Person Register', 'https://www.gov.uk/building-regulations-competent-person-schemes', 'government', 'self-certification scheme information for relevant building work'),
    ],
    relatedIndustries: ['electrical-contractors', 'building-contractors', 'roofing-contractors'],
  },
  {
    slug: 'electrical-contractors',
    name: 'Electrical contractors',
    singularName: 'electrical contractor',
    group: 'Local and home services',
    shortDescription: 'Domestic and commercial electrical firms whose registration, work categories, service area, certification and fault-reporting routes must be accurately represented.',
    pageAudience: ['electrical business owners', 'approved contractors', 'local electrical teams'],
    decisionMakers: ['owner-manager', 'qualified supervisor', 'contracts manager'],
    commonServices: ['electrical inspections', 'consumer-unit replacement', 'fault finding', 'rewiring', 'lighting installation', 'EV charger installation', 'commercial maintenance', 'emergency electrical repairs'],
    buyerConcerns: ['which work categories and property types are covered', 'whether relevant scheme registration can be verified', 'which areas and response windows apply', 'inspection, certification and notification arrangements', 'how estimates and diagnostic charges work', 'how urgent electrical risks are reported'],
    actionPaths: ['request an electrical inspection', 'ask for an installation quote', 'book fault finding', 'contact the emergency response route'],
    automationBoundaries: ['electrical safety decisions require a competent person', 'scheme membership and work categories must be verified, not implied', 'fault estimates may change after testing exposes the cause'],
    trustedSources: [
      source('Electrical Competent Person register', 'https://www.electricalcompetentperson.co.uk/', 'official-directory', 'registered electrical businesses and work categories'),
      source('NICEIC contractor search', 'https://niceic.com/find-a-tradesperson/', 'official-directory', 'NICEIC-certified business discovery where applicable'),
      source('NAPIT member search', 'https://search.napit.org.uk/', 'official-directory', 'NAPIT member verification where applicable'),
      source('Electrical Safety First', 'https://www.electricalsafetyfirst.org.uk/find-an-electrician/', 'professional-body', 'consumer guidance for finding registered electricians'),
    ],
    relatedIndustries: ['plumbing-heating-firms', 'building-contractors', 'roofing-contractors'],
  },
  {
    slug: 'roofing-contractors',
    name: 'Roofing contractors',
    singularName: 'roofing contractor',
    group: 'Local and home services',
    shortDescription: 'Roofing firms whose roof-system experience, inspection process, work-at-height controls, scheme status, guarantees and quote pathway need disciplined evidence.',
    pageAudience: ['roofing business owners', 'specialist contractors', 'regional roofing teams'],
    decisionMakers: ['owner-manager', 'contracts director', 'surveying lead'],
    commonServices: ['roof inspections', 'slate roof repairs', 'tile roof repairs', 'flat roofing', 'leadwork', 'gutter replacement', 'roof replacement', 'commercial roof maintenance'],
    buyerConcerns: ['which roof systems and building types the contractor handles', 'survey and quotation process', 'trade-body or scheme membership where claimed', 'insurance, guarantees and subcontracting arrangements', 'safe access and work-at-height planning', 'service area and emergency weather response'],
    actionPaths: ['request a roof inspection', 'submit photographs for initial triage', 'ask for a replacement quotation', 'report an urgent leak'],
    automationBoundaries: ['roof condition and safe access require a competent site assessment', 'membership, insurance and guarantee claims must be verified', 'storm response and temporary works depend on weather and safe availability'],
    trustedSources: [
      source('NFRC Find a Member', 'https://www.nfrc.co.uk/find-a-member', 'professional-body', 'NFRC member contractor discovery where applicable'),
      source('CompetentRoofer', 'https://www.competentroofer.co.uk/find-a-roofer/', 'official-directory', 'scheme member discovery and relevant self-certification'),
      source('TrustMark business directory', 'https://www.trustmark.org.uk/homeowner/find-a-tradesperson', 'official-directory', 'government-endorsed quality-scheme business discovery'),
      source('HSE work at height guidance', 'https://www.hse.gov.uk/construction/faq-height.htm', 'government', 'work-at-height planning and competence expectations'),
    ],
    relatedIndustries: ['building-contractors', 'plumbing-heating-firms', 'electrical-contractors'],
  },
  {
    slug: 'building-contractors',
    name: 'Building contractors',
    singularName: 'building contractor',
    group: 'Local and home services',
    shortDescription: 'Residential and commercial builders whose project scope, geographic coverage, permissions, trade responsibilities and estimate-to-contract pathway need transparent boundaries.',
    pageAudience: ['building company owners', 'main contractors', 'design-and-build teams'],
    decisionMakers: ['managing director', 'contracts manager', 'commercial manager'],
    commonServices: ['home extensions', 'renovations', 'loft conversions', 'new-build projects', 'commercial fit-outs', 'structural alterations', 'project management', 'planned maintenance'],
    buyerConcerns: ['which project sizes, sectors and locations are served', 'who manages design, permissions and building control', 'how estimates, allowances and variations are handled', 'insurance, warranties and subcontractor responsibilities', 'programme, access and site-safety expectations', 'how to submit plans and request an initial review'],
    actionPaths: ['submit a project brief', 'request a site visit', 'ask for budget and programme guidance', 'start a tender or pre-construction conversation'],
    automationBoundaries: ['project feasibility and pricing require drawings, site evidence and professional review', 'planning permission and building-control approval cannot be promised', 'structural, safety and contractual decisions require qualified humans'],
    trustedSources: [
      source('TrustMark business directory', 'https://www.trustmark.org.uk/homeowner/find-a-tradesperson', 'official-directory', 'scheme business discovery where applicable'),
      source('GOV.UK Competent Person Register', 'https://www.gov.uk/building-regulations-competent-person-schemes', 'government', 'self-certification scheme information for relevant work'),
      source('Planning Portal', 'https://www.planningportal.co.uk/', 'primary-industry-source', 'planning and building-control information for England and Wales'),
      source('HSE construction guidance', 'https://www.hse.gov.uk/construction/', 'government', 'construction health and safety duties and guidance'),
    ],
    relatedIndustries: ['roofing-contractors', 'electrical-contractors', 'plumbing-heating-firms'],
  },
  {
    slug: 'landscaping-companies',
    name: 'Landscaping companies',
    singularName: 'landscaping company',
    group: 'Local and home services',
    shortDescription: 'Garden design, build and maintenance companies whose service mix, design credentials, coverage, waste handling and quote process need clear separation.',
    pageAudience: ['landscaping business owners', 'garden designers', 'grounds-maintenance teams'],
    decisionMakers: ['owner-manager', 'design director', 'contracts manager'],
    commonServices: ['garden design', 'hard landscaping', 'soft landscaping', 'patios and paving', 'fencing', 'planting schemes', 'grounds maintenance', 'drainage and irrigation'],
    buyerConcerns: ['whether design, construction or maintenance is in scope', 'service area and minimum project size', 'designer or trade-body credentials where claimed', 'survey, concept and quotation stages', 'materials, waste and subcontractor responsibilities', 'seasonal availability and maintenance options'],
    actionPaths: ['request a garden consultation', 'submit photographs and measurements', 'ask for a maintenance proposal', 'book a site survey'],
    automationBoundaries: ['design and drainage decisions require site-specific review', 'planning, ecology and tree constraints may require specialist advice', 'waste-carrier and professional membership claims must be verified'],
    trustedSources: [
      source('BALI member directory', 'https://www.bali.org.uk/find-a-member/', 'professional-body', 'landscape professional member discovery where applicable'),
      source('Landscape Institute directory', 'https://my.landscapeinstitute.org/directory', 'official-directory', 'registered practice and professional discovery'),
      source('RHS Find a designer', 'https://www.rhs.org.uk/advice/find-a-professional', 'professional-body', 'garden professional discovery and consumer guidance'),
      source('HSE agriculture and horticulture guidance', 'https://www.hse.gov.uk/agriculture/topics/landscaping.htm', 'government', 'landscaping health and safety guidance'),
    ],
    relatedIndustries: ['building-contractors', 'roofing-contractors', 'commercial-cleaning-companies'],
  },
  {
    slug: 'commercial-cleaning-companies',
    name: 'Commercial cleaning companies',
    singularName: 'commercial cleaning company',
    group: 'Business services',
    shortDescription: 'Contract cleaning providers whose premises coverage, cleaning specification, staffing model, chemical controls, service hours and site-survey route must be explicit.',
    pageAudience: ['cleaning-company owners', 'facilities-service providers', 'contract cleaning teams'],
    decisionMakers: ['managing director', 'operations manager', 'contracts manager'],
    commonServices: ['office cleaning', 'clinical-area cleaning', 'school cleaning', 'retail cleaning', 'industrial cleaning', 'window cleaning', 'deep cleaning', 'washroom services'],
    buyerConcerns: ['which premises types and locations are covered', 'how a cleaning specification and frequency are agreed', 'staff vetting, supervision and absence cover', 'chemical, equipment and COSHH controls', 'quality checks, issue escalation and reporting', 'how to arrange a site survey and proposal'],
    actionPaths: ['request a site survey', 'submit a cleaning specification', 'ask for a mobilisation proposal', 'report an urgent service issue'],
    automationBoundaries: ['pricing requires premises, frequency and access details', 'safeguarding, keys and site-security decisions require human approval', 'chemical methods and risk assessments need competent oversight'],
    trustedSources: [
      source('British Institute of Cleaning Science', 'https://www.bics.org.uk/', 'professional-body', 'professional standards, training and sector resources'),
      source('HSE COSHH guidance', 'https://www.hse.gov.uk/coshh/', 'government', 'control of substances hazardous to health'),
      source('Environment Agency waste carrier register', 'https://environment.data.gov.uk/public-register/view/search-waste-carriers-brokers', 'official-directory', 'waste carrier and broker registration where applicable'),
      source('Living Wage Employer directory', 'https://www.livingwage.org.uk/accredited-living-wage-employers', 'official-directory', 'accredited Living Wage employer status where claimed'),
    ],
    relatedIndustries: ['managed-it-service-providers', 'recruitment-agencies', 'landscaping-companies'],
  },
];
